ALTER TABLE users ADD COLUMN roll_number VARCHAR(50) UNIQUE;
ALTER TABLE users ADD COLUMN semester INTEGER;
ALTER TABLE users ADD COLUMN program VARCHAR(50);
ALTER TABLE users ADD COLUMN employee_id VARCHAR(50) UNIQUE;
ALTER TABLE users ADD COLUMN department VARCHAR(100);
ALTER TABLE users ADD COLUMN max_capacity INTEGER;
